---
- name: Update sshd_config
  hosts: all
  become: true
  tasks:
    - name: Replace PasswordAuthentication line in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^#PasswordAuthentication yes
        line: PasswordAuthentication no
    - name: Reload sshd
      service:
        name: httpd
        state: reloaded
    - name: Create directory /opt
      file:
        path: /opt/jenkins
        state: directory
        mode: "0777"
