---
- name: cha3.110.132.97nge line & create directory & install java & restart sshd
  hosts: all
  become: yes
  tasks:
  - name: change line
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication no'
      line: PasswordAuthentication yes
      state: present
  - name: restart sshd
    systemd:
      name: sshd
      state: reloaded
  - name: Create the directory
    command: mkdir /opt/jenkins
  - name: give pemission to jenkins
    command: chmod 777 /opt/jenkins
  - name: install java
    command: apt install openjdk-8-jdk -y
