---
- name: change line & create directory & install java & restart sshd
  hosts: 52.66.196.170
  become: yes
  tasks:
  - name: change line
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication no'
      line: Password Authentication yes
      state: present
  - name: restart sshd
    systemd:
      name: sshd
      state: reloaded
  - name: Create the directory
    file:
      path: /var/jenkins
      state: directory
      mode: "0777"
  - name: install java
    command: yum install java-11-openjdk-devel -y
        
