- name: slave configuration
  hosts: all
  become: true
  tasks:
    - name: apt update
    - name: make directory
      command: /opt/jenkins
    - name: give permission
      command: chmod 777 /opt/jenkins
    - name: install java
      command: apt install openjdk-8-jdk -y
    - name: install java
      command: apt-get install fontconfig openjdk-11-jre -y
      
      
