---
- name: 
  hosts: 13.233.143.34
  become: true
  tasks:
    - name: install java
      command: yum install java-11-openjdk-devel -y
    - name: Create directory
      file:
        path: /opt/slave
        state: directory  
